<?php
include '../koneksi.php';
$idjadwal = $_GET['id_jadwal'];

mysqli_query($koneksi, "INSERT INTO kursi VALUES('','A1','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','A2','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','A3','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','A4','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','A5','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','A6','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','A7','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','A8','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','A9','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','A10','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','B1','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','B2','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','B3','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','B4','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','B5','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','B6','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','B7','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','B8','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','B9','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','B10','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','C1','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','C2','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','C3','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','C4','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','C5','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','C6','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','C7','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','C8','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','C9','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','C10','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','D1','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','D2','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','D3','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','D4','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','D5','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','D6','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','D7','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','D8','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','D9','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','D10','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','E1','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','E2','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','E3','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','E4','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','E5','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','E6','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','E7','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','E8','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','E9','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','E10','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','F1','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','F2','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','F3','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','F4','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','F5','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','F6','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','F7','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','F8','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','F9','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','F10','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','G1','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','G2','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','G3','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','G4','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','G5','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','G6','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','G7','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','G8','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','G9','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','G10','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','H1','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','H2','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','H3','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','H4','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','H5','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','H6','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','H7','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','H8','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','H9','','$idjadwal')");
mysqli_query($koneksi, "INSERT INTO kursi VALUES('','H10','','$idjadwal')");

header("location:jadwal_index.php?pesan=berhasil");

?>